common: &common
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV['TRAVIS'] ? 'postgres' : 'postman' %>
  password: <%= ENV['TRAVIS'] ? '' : 'postman' %>
  
development:
  database: postman_development
  <<: *common

test:
  database: postman_test
  <<: *common

production:
  database: postman_production
  <<: *common
